title: Jayanta Biswas
logo: /assest/img/profile_1.png
description: Spatial Geographer | MURP
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
